# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backend.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='backend.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rbackend.proto\"(\n\x08inputMsg\x12\x12\n\x05input\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_input\"+\n\toutputMsg\x12\x13\n\x06output\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\t\n\x07_output26\n\nbackendApi\x12(\n\rsendProductDB\x12\t.inputMsg\x1a\n.outputMsg\"\x00\x62\x06proto3'
)




_INPUTMSG = _descriptor.Descriptor(
  name='inputMsg',
  full_name='inputMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='input', full_name='inputMsg.input', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_input', full_name='inputMsg._input',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=17,
  serialized_end=57,
)


_OUTPUTMSG = _descriptor.Descriptor(
  name='outputMsg',
  full_name='outputMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='output', full_name='outputMsg.output', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_output', full_name='outputMsg._output',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=59,
  serialized_end=102,
)

_INPUTMSG.oneofs_by_name['_input'].fields.append(
  _INPUTMSG.fields_by_name['input'])
_INPUTMSG.fields_by_name['input'].containing_oneof = _INPUTMSG.oneofs_by_name['_input']
_OUTPUTMSG.oneofs_by_name['_output'].fields.append(
  _OUTPUTMSG.fields_by_name['output'])
_OUTPUTMSG.fields_by_name['output'].containing_oneof = _OUTPUTMSG.oneofs_by_name['_output']
DESCRIPTOR.message_types_by_name['inputMsg'] = _INPUTMSG
DESCRIPTOR.message_types_by_name['outputMsg'] = _OUTPUTMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

inputMsg = _reflection.GeneratedProtocolMessageType('inputMsg', (_message.Message,), {
  'DESCRIPTOR' : _INPUTMSG,
  '__module__' : 'backend_pb2'
  # @@protoc_insertion_point(class_scope:inputMsg)
  })
_sym_db.RegisterMessage(inputMsg)

outputMsg = _reflection.GeneratedProtocolMessageType('outputMsg', (_message.Message,), {
  'DESCRIPTOR' : _OUTPUTMSG,
  '__module__' : 'backend_pb2'
  # @@protoc_insertion_point(class_scope:outputMsg)
  })
_sym_db.RegisterMessage(outputMsg)



_BACKENDAPI = _descriptor.ServiceDescriptor(
  name='backendApi',
  full_name='backendApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=104,
  serialized_end=158,
  methods=[
  _descriptor.MethodDescriptor(
    name='sendProductDB',
    full_name='backendApi.sendProductDB',
    index=0,
    containing_service=None,
    input_type=_INPUTMSG,
    output_type=_OUTPUTMSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BACKENDAPI)

DESCRIPTOR.services_by_name['backendApi'] = _BACKENDAPI

# @@protoc_insertion_point(module_scope)
