# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import backend_pb2 as backend__pb2


class backendApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sendProductDB = channel.unary_unary(
                '/backendApi/sendProductDB',
                request_serializer=backend__pb2.inputMsg.SerializeToString,
                response_deserializer=backend__pb2.outputMsg.FromString,
                )


class backendApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def sendProductDB(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_backendApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sendProductDB': grpc.unary_unary_rpc_method_handler(
                    servicer.sendProductDB,
                    request_deserializer=backend__pb2.inputMsg.FromString,
                    response_serializer=backend__pb2.outputMsg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'backendApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class backendApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def sendProductDB(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/backendApi/sendProductDB',
            backend__pb2.inputMsg.SerializeToString,
            backend__pb2.outputMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
