# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='customer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x63ustomer.proto\"+\n\tinputMsg1\x12\x13\n\x06input1\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\t\n\x07_input1\".\n\noutputMsg1\x12\x14\n\x07output1\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_output12:\n\x0b\x63ustomerApi\x12+\n\x0esendCustomerDB\x12\n.inputMsg1\x1a\x0b.outputMsg1\"\x00\x62\x06proto3'
)




_INPUTMSG1 = _descriptor.Descriptor(
  name='inputMsg1',
  full_name='inputMsg1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='input1', full_name='inputMsg1.input1', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_input1', full_name='inputMsg1._input1',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=18,
  serialized_end=61,
)


_OUTPUTMSG1 = _descriptor.Descriptor(
  name='outputMsg1',
  full_name='outputMsg1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='output1', full_name='outputMsg1.output1', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_output1', full_name='outputMsg1._output1',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=63,
  serialized_end=109,
)

_INPUTMSG1.oneofs_by_name['_input1'].fields.append(
  _INPUTMSG1.fields_by_name['input1'])
_INPUTMSG1.fields_by_name['input1'].containing_oneof = _INPUTMSG1.oneofs_by_name['_input1']
_OUTPUTMSG1.oneofs_by_name['_output1'].fields.append(
  _OUTPUTMSG1.fields_by_name['output1'])
_OUTPUTMSG1.fields_by_name['output1'].containing_oneof = _OUTPUTMSG1.oneofs_by_name['_output1']
DESCRIPTOR.message_types_by_name['inputMsg1'] = _INPUTMSG1
DESCRIPTOR.message_types_by_name['outputMsg1'] = _OUTPUTMSG1
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

inputMsg1 = _reflection.GeneratedProtocolMessageType('inputMsg1', (_message.Message,), {
  'DESCRIPTOR' : _INPUTMSG1,
  '__module__' : 'customer_pb2'
  # @@protoc_insertion_point(class_scope:inputMsg1)
  })
_sym_db.RegisterMessage(inputMsg1)

outputMsg1 = _reflection.GeneratedProtocolMessageType('outputMsg1', (_message.Message,), {
  'DESCRIPTOR' : _OUTPUTMSG1,
  '__module__' : 'customer_pb2'
  # @@protoc_insertion_point(class_scope:outputMsg1)
  })
_sym_db.RegisterMessage(outputMsg1)



_CUSTOMERAPI = _descriptor.ServiceDescriptor(
  name='customerApi',
  full_name='customerApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=111,
  serialized_end=169,
  methods=[
  _descriptor.MethodDescriptor(
    name='sendCustomerDB',
    full_name='customerApi.sendCustomerDB',
    index=0,
    containing_service=None,
    input_type=_INPUTMSG1,
    output_type=_OUTPUTMSG1,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CUSTOMERAPI)

DESCRIPTOR.services_by_name['customerApi'] = _CUSTOMERAPI

# @@protoc_insertion_point(module_scope)
