# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import customer_pb2 as customer__pb2


class customerApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sendCustomerDB = channel.unary_unary(
                '/customerApi/sendCustomerDB',
                request_serializer=customer__pb2.inputMsg1.SerializeToString,
                response_deserializer=customer__pb2.outputMsg1.FromString,
                )


class customerApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def sendCustomerDB(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_customerApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sendCustomerDB': grpc.unary_unary_rpc_method_handler(
                    servicer.sendCustomerDB,
                    request_deserializer=customer__pb2.inputMsg1.FromString,
                    response_serializer=customer__pb2.outputMsg1.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'customerApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class customerApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def sendCustomerDB(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customerApi/sendCustomerDB',
            customer__pb2.inputMsg1.SerializeToString,
            customer__pb2.outputMsg1.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
